name: tezos_dart
description: >-
  A flutter package which provides the functionalities to play around with tezos dApps
version: 0.0.1
homepage: https://github.com/Tezsure/tezos_dart

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^2.1.4
  bs58check: ^1.0.1
  blake2b: ^0.1.2
  flutter_sodium: ^0.0.11
  bip39: ^1.0.3
  unorm_dart: ^0.1.2
  password_hash: ^2.0.0
  convert: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter